<?php
require_once("include/class/upload_class.php");
require_once("include/class/cls_date.php");
require_once("include/class/cls_tbl_seccion.php");
require_once("include/class/cls_tbl_album.php");
require_once("include/class/cls_tbl_newsletter.php");
require_once("include/class/cls_tbl_banner.php");
require_once("include/class/cls_tbl_contacto.php");
require_once("include/class/cls_tbl_pasajes.php");
require_once("include/class/cls_tbl_departamentos.php");
require_once("include/class/cls_tbl_empresas.php");
require_once("include/class/cls_tbl_contenido.php");
require_once("include/class/cls_tbl_hoteles.php");
require_once("include/class/cls_tbl_testimonios.php");
require_once("include/class/cls_tbl_paquete.php");
require_once("include/class/cls_tbl_categoria.php");
require_once("include/class/cls_yt_video.php");
require_once("include/class/cls_tbl_video.php");
require_once("include/class/cls_tbl_destino.php");
require_once("include/class/cls_tbl_tours.php");
require_once("include/class/cls_tbl_aeropuerto.php");
require_once("include/class/cls.date.language.php");
require_once("include/class/cls_tbl_language.php");

?>